import React from 'react';
import { Shell } from '@/components/layout/Shell';
import { Badge } from '@/components/ui/Badge';
import { TableContainer, Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/Table';
import { createAdminClient } from '@/lib/supabase/admin';
import { requireAuth } from '@/lib/auth';
import type { AuditLogRow } from '@/lib/schemas';

export const dynamic = 'force-dynamic';

const adminNavItems = [
  { label: 'Dashboard', href: '/admin', icon: '📊' },
  { label: 'Teams & Members', href: '/admin/teams', icon: '👥' },
  { label: 'Evaluators & Jury', href: '/admin/evaluators', icon: '🎓' },
  { label: 'Criteria Builder', href: '/admin/criteria', icon: '🎯' },
  { label: 'Round 1 Mapping', href: '/admin/assignments', icon: '📌' },
  { label: 'Audit Trail', href: '/admin/audit', icon: '🛡️' },
  { label: 'Merit & Reports', href: '/reports', icon: '🏆' },
];

export default async function AdminAuditPage() {
  const session = await requireAuth(['admin', 'data_operator']);
  let logs: AuditLogRow[] = [];

  try {
    const supabase = createAdminClient();
    const { data: fetchedLogs } = await supabase
      .from('audit_log')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50);

    if (fetchedLogs && fetchedLogs.length > 0) {
      logs = fetchedLogs;
    }
  } catch (err) {
    console.error('Failed to fetch audit log:', err);
  }

  // Fallback demo audit entries if DB is empty
  if (logs.length === 0) {
    // Use fixed ISO strings for demo data - avoids render impurity from Date.now()
    const oneHourAgo = new Date('2026-08-20T00:00:00.000Z').toISOString();
    const twoHoursAgo = new Date('2026-08-19T23:00:00.000Z').toISOString();
    logs = [
      {
        id: 'log-1',
        table_name: 'round1_scores',
        operation: 'INSERT',
        performed_by: '00000000-0000-0000-0000-000000000001',
        created_at: oneHourAgo,
        new_value: { team_id: 'team-1', score: 24, criteria_id: 'c1' },
      },
      {
        id: 'log-2',
        table_name: 'round2_scores',
        operation: 'INSERT',
        performed_by: '00000000-0000-0000-0000-000000000002',
        created_at: twoHoursAgo,
        new_value: { team_id: 'team-1', score: 38, criteria_id: 'c5' },
      },
    ];
  }

  return (
    <Shell
      title="Immutable Audit Log"
      roleName={session.role === 'admin' ? 'SIH Super Admin' : 'Data Operator'}
      roleType="admin"
      userName={session.name}
      navItems={adminNavItems}
    >
      <div>
        <h1 className="text-2xl font-black text-slate-100">Database DML Audit Log</h1>
        <p className="text-xs text-slate-400">
          Automatic record of score submissions and modifications generated by `fn_audit_scores()` trigger
        </p>
      </div>

      <TableContainer>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Timestamp</TableHead>
              <TableHead>Operation</TableHead>
              <TableHead>Target Table</TableHead>
              <TableHead>Performed By (UID)</TableHead>
              <TableHead>Value Payload Snapshot</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {logs.map((log) => (
              <TableRow key={log.id}>
                <TableCell className="font-mono text-xs text-slate-400">
                  {new Date(log.created_at).toLocaleString()}
                </TableCell>
                <TableCell>
                  <Badge variant={log.operation === 'INSERT' ? 'cyan' : 'amber'} glow>
                    {log.operation}
                  </Badge>
                </TableCell>
                <TableCell className="font-mono text-slate-200 text-xs">
                  {log.table_name}
                </TableCell>
                <TableCell className="font-mono text-[11px] text-cyan-400">
                  {log.performed_by || 'System / Service Role'}
                </TableCell>
                <TableCell>
                  <pre className="text-[10px] font-mono text-slate-400 bg-slate-950 p-1.5 rounded border border-slate-800 max-w-xs overflow-x-auto">
                    {JSON.stringify(log.new_value || log.old_value, null, 2)}
                  </pre>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </Shell>
  );
}
