import React from 'react';
import { Shell } from '@/components/layout/Shell';
import { Badge } from '@/components/ui/Badge';
import { requireAuth } from '@/lib/auth';
import { createAdminClient } from '@/lib/supabase/admin';
import { AuditClientWrapper } from '@/components/admin/AuditClientWrapper';
import type { AuditLogRow } from '@/lib/schemas';

export const dynamic = 'force-dynamic';

const adminNavItems = [
  { label: 'Dashboard', href: '/admin', icon: '📊' },
  { label: 'Teams & Members', href: '/admin/teams', icon: '👥' },
  { label: 'Problem Statements', href: '/admin/problem-statements', icon: '📋' },
  { label: 'Evaluators & Jury', href: '/admin/evaluators', icon: '🎓' },
  { label: 'Criteria Builder', href: '/admin/criteria', icon: '🎯' },
  { label: 'Round 1 / Round 2 Mapping', href: '/admin/assignments', icon: '📌' },
  { label: 'Audit Trail', href: '/admin/audit', icon: '🛡️' },
  { label: 'Merit & Reports', href: '/reports', icon: '🏆' },
];

export default async function AdminAuditPage() {
  const session = await requireAuth(['admin', 'data_operator']);
  let logs: AuditLogRow[] = [];

  try {
    const supabase = createAdminClient();
    const { data: fetchedLogs } = await supabase
      .from('audit_log')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50);

    if (fetchedLogs && fetchedLogs.length > 0) {
      logs = fetchedLogs;
    }
  } catch (err) {
    console.error('Failed to fetch audit log:', err);
  }

  // Fallback demo audit entries removed

  return (
    <Shell
      title="Immutable Audit Log"
      roleName={session.role === 'admin' ? 'SIH Super Admin' : 'Data Operator'}
      roleType="admin"
      userName={session.name}
      navItems={adminNavItems}
    >
      <div>
        <h1 className="text-2xl font-black text-slate-900">Database DML Audit Log</h1>
        <p className="text-xs text-slate-500">
          Automatic record of score submissions and modifications generated by `fn_audit_scores()` trigger
        </p>
      </div>

      <AuditClientWrapper initialLogs={logs} />
    </Shell>
  );
}
