import React from 'react';
import { Shell } from '@/components/layout/Shell';
import { Badge } from '@/components/ui/Badge';
import { requireAuth } from '@/lib/auth';
import { createAdminClient } from '@/lib/supabase/admin';
import { AuditClientWrapper } from '@/components/admin/AuditClientWrapper';
import type { AuditLogRow } from '@/lib/schemas';

export const dynamic = 'force-dynamic';

import { adminNavItems } from '@/lib/nav';

export default async function AdminAuditPage() {
  const session = await requireAuth(['admin', 'data_operator']);
  
  let logs: AuditLogRow[] = [];

  try {
    const supabase = createAdminClient();
    const { data: fetchedLogs } = await supabase
      .from('audit_log')
      .select('id, operation, table_name, performed_by, row_id, old_value, new_value, created_at')
      .order('created_at', { ascending: false })
      .limit(50);

    if (fetchedLogs && fetchedLogs.length > 0) {
      logs = fetchedLogs;
    }
  } catch (err) {
    console.error('Failed to fetch audit log:', err);
  }

  // Fallback demo audit entries removed

  return (
    <Shell
      title="Immutable Audit Log"
      roleName={session.role === 'admin' ? 'SIH Super Admin' : 'Data Operator'}
      roleType="admin"
      userName={session.name}
      navItems={adminNavItems}
    >
      <div>
        <h1 className="text-2xl font-black text-slate-900">Database DML Audit Log</h1>
        <p className="text-xs text-slate-500">
          Automatic record of score submissions and modifications generated by `fn_audit_scores()` trigger
        </p>
      </div>

      <AuditClientWrapper initialLogs={logs} />
    </Shell>
  );
}
